(define (foo x y z)
  (define (sqr-lst lst)
    (map square lst))
  (define (largest-lst x y z)
    (if (> x y)
        (if (> y z)
            (list x y)
            (list x z))
        (if (> x z)
            (list x y)
            (list y z))))
  (define (add-lst lst)
    (reduce + 0 lst))
  (add-lst (sqr-lst (largest-lst x y z))))
