(define (same-parity x . z)
  (define (same-parity-rec rest)
    (cond ((null? rest) rest)
          ((and (even? x) (even? (first rest)))
           (cons (first rest) (same-parity-rec (cdr rest))))
          ((even? x) (same-parity-rec (cdr rest)))
          ((and (odd? x) (odd? (first rest)))
           (cons (first rest) (same-parity-rec (cdr rest))))
          ((odd? x) (same-parity-rec (cdr rest)))))
  (cons x (same-parity-rec z)))
